<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Agentforce Studio</label>
    <navType>Console</navType>
    <tabs>standard-AgentforceStudio</tabs>
    <tabs>childd1__c</tabs>
    <tabs>manPar1__c</tabs>
    <tabs>manPar2__c</tabs>
    <tabs>manPar3__c</tabs>
    <tabs>manPar4__c</tabs>
    <tabs>manPar5__c</tabs>
    <tabs>manPar6__c</tabs>
    <tabs>manPar7__c</tabs>
    <tabs>manPar8__c</tabs>
    <tabs>manPar9__c</tabs>
    <tabs>manPar10__c</tabs>
    <tabs>manPar11__c</tabs>
    <tabs>manPar12__c</tabs>
    <tabs>manPar13__c</tabs>
    <tabs>manPar14__c</tabs>
    <tabs>manPar15__c</tabs>
    <tabs>manPar16__c</tabs>
    <tabs>manPar17__c</tabs>
    <tabs>manPar18__c</tabs>
    <tabs>manPar19__c</tabs>
    <tabs>manPar20__c</tabs>
    <tabs>manRoot__c</tabs>
    <tabs>TestObjectA__c</tabs>
    <tabs>TestObjectB__c</tabs>
    <tabs>manageid1__c</tabs>
    <tabs>manageidP__c</tabs>
    <tabs>search1__c</tabs>
    <tabs>richObj__c</tabs>
    <tabs>MichalTest__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>MichalTest__c</tab>
        </mappings>
        <mappings>
            <tab>TestObjectA__c</tab>
        </mappings>
        <mappings>
            <tab>TestObjectB__c</tab>
        </mappings>
        <mappings>
            <tab>childd1__c</tab>
        </mappings>
        <mappings>
            <tab>manPar10__c</tab>
        </mappings>
        <mappings>
            <tab>manPar11__c</tab>
        </mappings>
        <mappings>
            <tab>manPar12__c</tab>
        </mappings>
        <mappings>
            <tab>manPar13__c</tab>
        </mappings>
        <mappings>
            <tab>manPar14__c</tab>
        </mappings>
        <mappings>
            <tab>manPar15__c</tab>
        </mappings>
        <mappings>
            <tab>manPar16__c</tab>
        </mappings>
        <mappings>
            <tab>manPar17__c</tab>
        </mappings>
        <mappings>
            <tab>manPar18__c</tab>
        </mappings>
        <mappings>
            <tab>manPar19__c</tab>
        </mappings>
        <mappings>
            <tab>manPar1__c</tab>
        </mappings>
        <mappings>
            <tab>manPar20__c</tab>
        </mappings>
        <mappings>
            <tab>manPar2__c</tab>
        </mappings>
        <mappings>
            <tab>manPar3__c</tab>
        </mappings>
        <mappings>
            <tab>manPar4__c</tab>
        </mappings>
        <mappings>
            <tab>manPar5__c</tab>
        </mappings>
        <mappings>
            <tab>manPar6__c</tab>
        </mappings>
        <mappings>
            <tab>manPar7__c</tab>
        </mappings>
        <mappings>
            <tab>manPar8__c</tab>
        </mappings>
        <mappings>
            <tab>manPar9__c</tab>
        </mappings>
        <mappings>
            <tab>manRoot__c</tab>
        </mappings>
        <mappings>
            <tab>manageid1__c</tab>
        </mappings>
        <mappings>
            <tab>manageidP__c</tab>
        </mappings>
        <mappings>
            <tab>richObj__c</tab>
        </mappings>
        <mappings>
            <tab>search1__c</tab>
        </mappings>
        <mappings>
            <tab>standard-AgentforceStudio</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
